# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-10-25 13:56
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0063_naiscompany'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='naiscompany',
            options={'verbose_name': '\u0417\u0430\u0432\u0434\u0430\u043d\u043d\u044f \u043d\u0430 \u0441\u0442\u0432\u043e\u0440\u0435\u043d\u043d\u044f \u043a\u043e\u043c\u043f\u0430\u043d\u0456\u0439 \u0437 \u041d\u0410\u0406\u0421', 'verbose_name_plural': '\u0417\u0430\u0432\u0434\u0430\u043d\u043d\u044f \u043d\u0430 \u0441\u0442\u0432\u043e\u0440\u0435\u043d\u043d\u044f \u043a\u043e\u043c\u043f\u0430\u043d\u0456\u0439 \u0437 \u041d\u0410\u0406\u0421'},
        ),
        migrations.AlterField(
            model_name='naiscompany',
            name='matched_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='\u0417\u0430\u043f\u0438\u0441 \u043d\u0430 \u0441\u0442\u0432\u043e\u0440\u0435\u043d\u043d\u044f'),
        ),
    ]
