# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-01-10 14:31
from __future__ import unicode_literals

from django.contrib.postgres.operations import HStoreExtension
from django.db import migrations

class Migration(migrations.Migration):
    dependencies = [
        ('tasks', '0064_auto_20191025_1656'),
    ]

    operations = [
        # HStoreExtension(),
    ]