from neomodel import StructuredNode, StringProperty, BooleanProperty, IntegerProperty


class Person(StructuredNode):
    description_en = StringProperty()
    description_uk = StringProperty()
    details_en = StringProperty()
    details_uk = StringProperty()
    full_name_en = StringProperty()
    full_name_uk = StringProperty()
    is_dead = BooleanProperty()
    is_pep = BooleanProperty()
    kind = StringProperty()
    kind_en = StringProperty()
    kind_uk = StringProperty()
    model = StringProperty()
    name_en = StringProperty()
    name_uk = StringProperty()
    pk = IntegerProperty(unique_index=True)
    reason_of_termination = IntegerProperty()
    type_of_official = IntegerProperty()
    url = StringProperty()
    url_en = StringProperty()
    url_uk = StringProperty()


class Company(StructuredNode):
    affiliated_with_pep = BooleanProperty()
    bank = BooleanProperty()
    details_en = StringProperty()
    details_uk = StringProperty()
    full_name_en = StringProperty()
    full_name_uk = StringProperty()
    is_closed = BooleanProperty()
    kind_en = StringProperty()
    kind_uk = StringProperty()
    model = StringProperty()
    name_en = StringProperty()
    name_uk = StringProperty()
    pk = IntegerProperty(unique_index=True)
    political_party = BooleanProperty()
    public_office = BooleanProperty()
    service_provider = BooleanProperty()
    state_company = BooleanProperty()
    state_enterprise = BooleanProperty()
    url_en = StringProperty()
    url_uk = StringProperty()


class Country(StructuredNode):
    details_en = StringProperty()
    details_uk = StringProperty()
    is_jurisdiction = BooleanProperty()
    iso2 = StringProperty()
    iso3 = StringProperty()
    model = StringProperty()
    name_en = StringProperty()
    name_uk = StringProperty()
    pk = IntegerProperty(unique_index=True)
    url_en = StringProperty()
    url_uk = StringProperty()
