# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-10-22 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0166_auto_20191022_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='template_en',
            field=models.TextField(blank=True, null=True, verbose_name='Template to render flag details'),
        ),
        migrations.AddField(
            model_name='rule',
            name='template_uk',
            field=models.TextField(blank=True, null=True, verbose_name='Template to render flag details'),
        ),
    ]
