# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-10-24 12:23
from __future__ import unicode_literals

import core.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import select2.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0168_auto_20191024_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='images', verbose_name='\u0413\u043e\u043b\u043e\u0432\u043d\u0430 \u0441\u0432\u0456\u0442\u043b\u0438\u043d\u0430')),
                ('caption', models.TextField(verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('caption_uk', models.TextField(null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('caption_en', models.TextField(null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('header', models.TextField(blank=True, verbose_name='\u041f\u0456\u0437\u0434\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('header_uk', models.TextField(blank=True, null=True, verbose_name='\u041f\u0456\u0437\u0434\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('header_en', models.TextField(blank=True, null=True, verbose_name='\u041f\u0456\u0437\u0434\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('text', core.fields.RedactorField(blank=True, verbose_name='\u0422\u0435\u043a\u0441\u0442')),
                ('text_uk', core.fields.RedactorField(blank=True, null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442')),
                ('text_en', core.fields.RedactorField(blank=True, null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442')),
                ('publish', models.BooleanField(default=False, verbose_name='\u041e\u043f\u0443\u0431\u043b\u0456\u043a\u043e\u0432\u0430\u043d\u043e')),
                ('date', models.DateField(verbose_name='\u0414\u0430\u0442\u0430 \u043f\u0443\u0431\u043b\u0456\u043a\u0430\u0446\u0456\u0457')),
                ('kind', models.CharField(choices=[('i', '\u0440\u043e\u0437\u0441\u043b\u0456\u0434\u0443\u0432\u0430\u043d\u043d\u044f'), ('b', '\u0431\u043b\u043e\u0433')], default='b', max_length=5, verbose_name='\u0422\u0438\u043f \u0441\u0442\u0430\u0442\u0442\u0456')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='\u041e\u0441\u0442\u0430\u043d\u043d\u044f \u0437\u043c\u0456\u043d\u0430')),
                ('last_editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='\u0410\u0432\u0442\u043e\u0440 \u043e\u0441\u0442\u0430\u043d\u043d\u044c\u043e\u0457 \u0437\u043c\u0456\u043d\u0438')),
                ('related_companies', select2.fields.ManyToManyField(sorted=False, to='core.Company', verbose_name="\u041f\u043e\u0432'\u044f\u0437\u0430\u043d\u0456 \u043a\u043e\u043c\u043f\u0430\u043d\u0456\u0457")),
                ('related_persons', select2.fields.ManyToManyField(sorted=False, to='core.Person', verbose_name="\u041f\u043e\u0432'\u044f\u0437\u0430\u043d\u0456 \u043e\u0441\u043e\u0431\u0438")),
            ],
            options={
                'verbose_name': '\u0421\u0442\u0430\u0442\u0442\u044f',
                'verbose_name_plural': '\u0421\u0442\u0430\u0442\u0442\u0456',
            },
        ),
        migrations.AlterModelOptions(
            name='flag',
            options={'verbose_name': '\u0427\u0435\u0440\u0432\u043e\u043d\u0438\u0439 \u043f\u0440\u0430\u043f\u043e\u0440\u0435\u0446\u044c', 'verbose_name_plural': '\u0427\u0435\u0440\u0432\u043e\u043d\u0456 \u043f\u0440\u0430\u043f\u043e\u0440\u0446\u0456'},
        ),
        migrations.AlterModelOptions(
            name='rule',
            options={'verbose_name': '\u041f\u0440\u0430\u0432\u0438\u043b\u043e \u0441\u043a\u043e\u0440\u0438\u043d\u0433\u0443', 'verbose_name_plural': '\u041f\u0440\u0430\u0432\u0438\u043b\u0430 \u0441\u043a\u043e\u0440\u0438\u043d\u0433\u0443'},
        ),
    ]
