# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-10-25 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0171_auto_20191025_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='kind',
            field=models.CharField(choices=[('i', '\u0440\u043e\u0437\u0441\u043b\u0456\u0434\u0443\u0432\u0430\u043d\u043d\u044f'), ('r', 'FAQ (\u0432\u0438\u0434\u0430\u043b\u0435\u043d\u043d\u044f)'), ('b', '\u0431\u043b\u043e\u0433'), ('f', 'FAQ (\u0437\u0430\u0433\u0430\u043b\u044c\u043d\u0438\u0439)')], default='b', max_length=5, verbose_name='\u0422\u0438\u043f \u0441\u0442\u0430\u0442\u0442\u0456'),
        ),
        migrations.AlterField(
            model_name='article',
            name='related_companies',
            field=models.ManyToManyField(blank=True, related_name='articles', to='core.Company', verbose_name="\u041f\u043e\u0432'\u044f\u0437\u0430\u043d\u0456 \u043a\u043e\u043c\u043f\u0430\u043d\u0456\u0457"),
        ),
        migrations.AlterField(
            model_name='article',
            name='related_persons',
            field=models.ManyToManyField(blank=True, related_name='articles', to='core.Person', verbose_name="\u041f\u043e\u0432'\u044f\u0437\u0430\u043d\u0456 \u043e\u0441\u043e\u0431\u0438"),
        ),
    ]
