# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-01-07 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0174_auto_20200102_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='person2company',
            name='category',
            field=models.CharField(choices=[('bank_customer', '\u043a\u043b\u0456\u0454\u043d\u0442 \u0431\u0430\u043d\u043a\u0443'), ('by_position', '\u0437\u0430 \u043f\u043e\u0441\u0430\u0434\u043e\u044e'), ('manager', '\u043a\u0435\u0440\u0456\u0432\u043d\u0438\u043a'), ('other', '\u0456\u043d\u0448\u0435'), ('owner', '\u0432\u043b\u0430\u0441\u043d\u0438\u043a')], default='other', max_length=15, verbose_name="\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0456\u044f \u0437\u0432'\u044f\u0437\u043a\u0443"),
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_watermarked',
            field=models.FileField(blank=True, max_length=1000, upload_to='documents/_', verbose_name='\u0424\u0430\u0439\u043b \u0437 \u0432\u043e\u0434\u044f\u043d\u0438\u043c \u0437\u043d\u0430\u043a\u043e\u043c'),
        ),
    ]
