# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-01-15 12:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0177_auto_20200110_1719'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exchangerate',
            options={'ordering': ('-dt',), 'verbose_name': '\u041a\u0443\u0440\u0441 \u0432\u0430\u043b\u044e\u0442', 'verbose_name_plural': '\u041a\u0443\u0440\u0441\u0438 \u0432\u0430\u043b\u044e\u0442'},
        ),
    ]
